# Generated by Django 5.2.6 on 2025-09-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=128)),
                ('matn', models.TextField()),
                ('image', models.ImageField(upload_to='post')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp4.add_post')),
            ],
        ),
    ]
